### ISSUE TITLE
Why's it called Dali?

### ISSUE THREAD

**Issue by kirtanechiron** [dali-ml/Dali#13]
Just curious...

**Comment by JonathanRaiman** [comment]
1. In the painting https://en.wikipedia.org/wiki/The_Persistence_of_Memory, Dali has clocks that are melting, and in Dali we wanted to also have time be "flexible" [e.g. back-propagate through control flow, search, data structures, and easily construct wild RNN architectures]!

2. Also, our take was that using an artist's name would help people be creative in their machine learning, and have out-of-the-box thinking, rather than going for a more technical/computation name like "TensorFlow", or "CGT" 😄

**Comment by kirtanechiron** [comment]
That's really cool. I'm actually exploring art generation with GANs right now so I can definitely appreciate that.
